export { default as DataTable } from './DataTable.vue'
export { default as DataTableHeader } from './DataTableHeader.vue'
export { default as DataTableRow } from './DataTableRow.vue'
export { default as DataTableCell } from './DataTableCell.vue'
export { default as DataTableHead } from './DataTableHead.vue'
export { default as DataTableBody } from './DataTableBody.vue' 