export { default as MainLayout } from './MainLayout.vue'
export { default as DashboardLayout } from './DashboardLayout.vue'
export { default as GridLayout } from './GridLayout.vue'
export { default as SplitLayout } from './SplitLayout.vue'
export { default as MasonryLayout } from './MasonryLayout.vue' 